ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS '; 
SET SERVEROUTPUT ON;
CREATE TABLE MAYTINH 
(
    MaMT VARCHAR2(10) PRIMARY KEY,
    TenMT VARCHAR2(50),
    MauSac VARCHAR2(50),
    DungLuong VARCHAR2(50),
    GiaTien NUMBER,
    ThuongHieu VARCHAR2(50)
);

CREATE TABLE CUAHANG
(
    MaCH VARCHAR2(5) PRIMARY KEY,
    TenCH VARCHAR2(50),
    SoDT VARCHAR2(11)
);

CREATE TABLE KHOHANG_QLKHO
(
    MaCH VARCHAR2(5),
    MaMT VARCHAR2(10),
    SoLuong NUMBER,
    NgayNhapKho DATE,
    CONSTRAINT PK_KHOHANG_QLKHO PRIMARY KEY(MaCH,MaMT),
    CONSTRAINT FK_KHOHANG_QLKHO_CUAHANG FOREIGN KEY (MaCH) REFERENCES CUAHANG (MaCH),
    CONSTRAINT FK_KHOHANG_QLKHO_MAYTINH FOREIGN KEY (MaMT) REFERENCES MAYTINH(MaMT)
);

CREATE TABLE KHOHANG_NVBH (
    MaCH VARCHAR2(5),
    MaMT VARCHAR2(10),
    TinhTrang VARCHAR2(10), 
    CONSTRAINT PK_KHOHANG_NVBH PRIMARY KEY(MaCH,MaMT), 
    CONSTRAINT FK_KHOHANG_NVBH_CUAHANG FOREIGN KEY (MaCH) REFERENCES CUAHANG (MaCH), 
    CONSTRAINT FK_KHOHANG_NVBH_MAYTINH FOREIGN KEY (MaMT) REFERENCES MAYTINH(MaMT)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(5) PRIMARY KEY, 
    TenNV VARCHAR2(50),
    DiaChi VARCHAR2(50),
    SoDT VARCHAR2(11),
    Luong NUMBER,
    MaCH VARCHAR2(5), 
    CONSTRAINT FK_NHANVIEN_CUAHANG FOREIGN KEY (MaCH) REFERENCES CUAHANG (MaCH)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(5) PRIMARY KEY, 
    TenKH VARCHAR2(50),
    DiaChi VARCHAR2(50),
    SoDT VARCHAR2(11)
);

CREATE TABLE HOADON 
(
    MaHD VARCHAR2(5) PRIMARY KEY, 
    MaNV VARCHAR2(5),
    MaKH VARCHAR2(5), 
    MaCH VARCHAR2(5), 
    NgayHD DATE,
    ThanhTien NUMBER,
    CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
    CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG (MaKH),
    CONSTRAINT FK_HOADON_CUAHANG FOREIGN KEY  (MaCH) REFERENCES CUAHANG (MaCH)
);

CREATE TABLE CTHD (
    MaHD VARCHAR2(5),
    MaMT VARCHAR2(10),
    SoLuong NUMBER, 
    CONSTRAINT PK_CTHD PRIMARY KEY(MaHD,MaMT),
    CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON (MaHD),
    CONSTRAINT FK_CTHD_MAYTINH FOREIGN KEY (MaMT) REFERENCES MAYTINH (MaMT)
);


-- Tao USER CH1
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER GiamDoc1 IDENTIFIED BY GiamDoc1;
GRANT CONNECT, CREATE PUBLIC DATABASE LINK TO GiamDoc1;
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.MAYTINH TO GiamDoc1; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.CUAHANG TO GiamDoc1; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.KHOHANG_QLKHO TO GiamDoc1;
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.KHOHANG_NVBH TO GiamDoc1;
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.NHANVIEN TO GiamDoc1; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.HOADON TO GiamDoc1; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.CTHD TO GiamDoc1; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CH1.KHACHHANG TO GiamDoc1; 
GRANT CREATE ANY TRIGGER TO GIAMDOC1;
GRANT CREATE ANY PROCEDURE TO GIAMDOC1;

CREATE USER TruongCH1 IDENTIFIED BY TruongCH1;
GRANT CONNECT, CREATE PUBLIC DATABASE LINK TO TruongCH1;
GRANT SELECT, INSERT, UPDATE ON CH1.KHOHANG_QLKHO TO TruongCH1; 
GRANT SELECT, INSERT, UPDATE ON CH1.KHOHANG_NVBH TO TruongCH1; 
GRANT SELECT ON CH1.MAYTINH TO TruongCH1;
GRANT SELECT, INSERT, UPDATE ON CH1.HOADON TO TruongCH1; 
GRANT SELECT, INSERT, UPDATE ON CH1.CTHD TO TruongCH1; 
GRANT SELECT, INSERT, UPDATE ON CH1.KHACHHANG TO TruongCH1;

CREATE USER QuanKho1 IDENTIFIED BY QuanKho1;
GRANT CONNECT, CREATE PUBLIC DATABASE LINK TO QuanKho1;
GRANT SELECT, INSERT, UPDATE ON CH1.KHOHANG_QLKHO TO QuanKho1; 
GRANT SELECT, INSERT, UPDATE ON CH1.MAYTINH TO QuanKho1; 
GRANT SELECT, INSERT, UPDATE ON CH1.KHOHANG_NVBH TO QuanKho1;

CREATE USER NhanVien1 IDENTIFIED BY NhanVien1;
GRANT CONNECT, CREATE PUBLIC DATABASE LINK TO NhanVien1;
GRANT SELECT ON CH1.KHOHANG_NVBH TO NhanVien1; 
GRANT SELECT ON CH1.MAYTINH TO NhanVien1; 
GRANT SELECT ON CH1.HOADON TO NhanVien1;
GRANT SELECT ON CH1.CTHD TO NhanVien1;
GRANT SELECT ON CH1.KHACHHANG TO NhanVien1;


-- Them du lieu CH1
-- Them du lieu bang MAYTINH
insert into MAYTINH values ('MT01','Dell Inspiron', 'Black', '256GB' ,20000000,'Dell');
insert into MAYTINH values ('MT02','Dell Vostro', 'Black', '512GB' ,19000000,'Dell');
insert into MAYTINH values ('MT03','Dell XPS', 'White', '1TB' ,18000000,'Dell');
insert into MAYTINH values ('MT04','Dell Alienware', 'Black', '512GB' ,22000000,'Dell');
insert into MAYTINH values ('MT05','Dell Latitude', 'Gray', '512GB' ,17000000,'Dell');
insert into MAYTINH values ('MT06','HP Spectre', 'Black', '512GB' ,20000000,'HP');
insert into MAYTINH values ('MT07','HP Envy', 'White', '1TB' ,25000000,'HP');
insert into MAYTINH values ('MT08','HP Pavilion', 'Black', '512GB' ,28000000,'HP');
insert into MAYTINH values ('MT09','HP Omen', 'Black', '512GB' ,23000000,'HP');
insert into MAYTINH values ('MT10','HP ZBook', 'Gray', '512GB' ,19500000,'HP');
insert into MAYTINH values ('MT11','ASUS ROG', 'Black', '512GB' ,27000000,'AUSUS');
insert into MAYTINH values ('MT12','ASUS TUF Gaming', 'Black', '512GB' ,26000000,'AUSUS');
insert into MAYTINH values ('MT13','ASUS ZenBook', 'Black', '512GB' ,21000000,'AUSUS');
insert into MAYTINH values ('MT14','ASUS VivoBook', 'Black', '512GB' ,16000000,'AUSUS');
insert into MAYTINH values ('MT15','ASUS ExpertBook', 'Black', '512GB' ,29000000,'AUSUS');
insert into MAYTINH values ('MT16','Acer Spin', 'Black', '64GB' ,15000000,'Acer');
insert into MAYTINH values ('MT17','Acer Aspire', 'Black', '64GB' ,20000000,'Acer');
insert into MAYTINH values ('MT18','Acer Nitro', 'Black', '64GB' ,21500000,'Acer');
insert into MAYTINH values ('MT19','Acer Swift', 'Black', '64GB' ,29500000,'Acer');
insert into MAYTINH values ('MT20','Acer Predator', 'Black', '64GB' ,34000000,'Acer');

--Them du lieu bang CUAHANG
insert into CUAHANG values('CH01','QUAN 1, TPHCM', '0358461912');

-- Them du lieu bang KHACHHANG
INSERT INTO CH1.KHACHHANG VALUES ('KH01', 'Nguyen Minh Quang', 'QUAN 1, TPHCM', '09494499969');
INSERT INTO CH1.KHACHHANG VALUES ('KH02', 'Nguyen Minh Tu', 'QUAN 2, TPHCM', '0995596624');
INSERT INTO CH1.KHACHHANG VALUES ('KH03', 'Nguyen Lam Minh Sang', 'QUAN 3, TPHCM', '09822343455');
INSERT INTO CH1.KHACHHANG VALUES ('KH04', 'Nguyen Duc Trung', 'QUAN 4, TPHCM', '0936934644');
INSERT INTO CH1.KHACHHANG VALUES ('KH05', 'Phan Thi Thu Cuc', 'QUAN 5, TPHCM', '0944924928');
INSERT INTO CH1.KHACHHANG VALUES ('KH06', 'Vo Hoang Vy', 'QUAN 6, TPHCM', '09494499969');
INSERT INTO CH1.KHACHHANG VALUES ('KH07', 'Huynh Gia Huy', 'QUAN 7, TPHCM', '0949821299');
INSERT INTO CH1.KHACHHANG VALUES ('KH08', 'Pham Duc Thuan', 'QUAN 8, TPHCM', '09494499969');
INSERT INTO CH1.KHACHHANG VALUES ('KH09', 'Dao Duy Khang', 'QUAN 9, TPHCM', '0982999343');
INSERT INTO CH1.KHACHHANG VALUES ('KH10', 'Le Vinh', 'QUAN 10, TPHCM', '0998555312');
INSERT INTO CH1.KHACHHANG VALUES ('KH11', 'Pham Minh Thien', 'QUAN 11, TPHCM', '0949423459');
INSERT INTO CH1.KHACHHANG VALUES ('KH12', 'Nguyen Quang Truong', 'QUAN 12, TPHCM', '09494445341');
INSERT INTO CH1.KHACHHANG VALUES ('KH13', 'Nguyen Nam Cam', 'TAN BINH, TPHCM', '09494434232');
INSERT INTO CH1.KHACHHANG VALUES ('KH14', 'Nguyen Bac Hai', 'TAN PHU, TPHCM', '09494456821');
INSERT INTO CH1.KHACHHANG VALUES ('KH15', 'Nguyen Phu Trong', 'HOC MON, TPHCM', '09494497645');
INSERT INTO CH1.KHACHHANG VALUES ('KH16', 'Nguyen Van Khai', 'BINH TAN, TPHCM', '09494348769');
INSERT INTO CH1.KHACHHANG VALUES ('KH17', 'Nguyen Cong Nhuan', 'THU DUC, TPHCM', '09491165469');
INSERT INTO CH1.KHACHHANG VALUES ('KH18', 'Nguyen Quang Minh', 'CAI BE, TPHCM', '09490098769');
INSERT INTO CH1.KHACHHANG VALUES ('KH19', 'Nguyen Cao Nhan', 'BINH CHANH, TPHCM', '09494123964');
INSERT INTO CH1.KHACHHANG VALUES ('KH20', 'Nguyen Duc Minh', 'BINH THANH, TPHCM', '09494495169');
-- Them du lieu bang NHANVIEN
INSERT INTO CH1.NHANVIEN VALUES ('NV01', 'Ngo Le Hoang Quyen','QUAN 1, TPHCM','09494499969',6300000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV02', 'Nguyen Thi Hai Vy','QUAN 2, TPHCM','09494499969',6500000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV03', 'Dang Thi Kim Ngan','QUAN 3, TPHCM','09494499969',7000000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV04', 'Huynh Thi Anh Tho','QUAN 4, TPHCM','09494499969',8000000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV05', 'Nguyen Ngoc Thanh Vy','QUAN 5, TPHCM','09494499969',6000000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV06', 'Nguyen Ngoc Truc Phuong','QUAN 6, TPHCM','09494499969',10000000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV07', 'Bui Duy Phi','QUAN 7, TPHCM','09494499969',12000000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV08', 'Ho Gia Huy','QUAN 8, TPHCM','09494499969',9300000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV09', 'Truong Gia Bao','QUAN 9, TPHCM','09494499969',7700000,'CH01');
INSERT INTO CH1.NHANVIEN VALUES ('NV10', 'Nguyen Tuan Khang','QUAN 10, TPHCM','09494499969',7500000,'CH01');

-- Them du lieu bang KHOHANG_QLKHO
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT01',100,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT02',200,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT03',50,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT04',10,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT05',20,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT06',40,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT07',100,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT08',150,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT09',180,'29/10/2022');
INSERT INTO CH1.KHOHANG_QLKHO VALUES ('CH01','MT10',30,'30/10/2022');

-- Them du lieu bang KHOHANG_NVBH
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT09','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT01','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT04','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT07','Het hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT02','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT03','Het hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT05','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT06','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT10','Con hang');
INSERT INTO CH1.KHOHANG_NVBH VALUES ('CH01','MT08','Het hang');

-- Them du lieu bang HOADON
INSERT INTO CH1.HOADON VALUES ('HD01','NV01','KH01','CH01','30/10/2022', 22390000);
INSERT INTO CH1.HOADON VALUES ('HD02','NV02','KH01','CH01','31/10/2022', 44780000);
INSERT INTO CH1.HOADON VALUES ('HD03','NV02','KH03','CH01','30/10/2022', 21590000);
INSERT INTO CH1.HOADON VALUES ('HD04','NV01','KH03','CH01','30/10/2022', 64770000);
INSERT INTO CH1.HOADON VALUES ('HD05','NV03','KH04','CH01','30/10/2022', 24190000);
INSERT INTO CH1.HOADON VALUES ('HD06','NV07','KH04','CH01','30/10/2022', 18290000);
INSERT INTO CH1.HOADON VALUES ('HD07','NV08','KH05','CH01','30/10/2022', 36580000);
INSERT INTO CH1.HOADON VALUES ('HD08','NV05','KH08','CH01','30/10/2022', 18290000);
INSERT INTO CH1.HOADON VALUES ('HD09','NV05','KH09','CH01','30/10/2022', 58770000);
INSERT INTO CH1.HOADON VALUES ('HD10','NV06','KH02','CH01','30/10/2022', 58170000);

-- Them du lieu bang CTHD
INSERT INTO CH1.CTHD VALUES ('HD01', 'MT09', 1);
INSERT INTO CH1.CTHD VALUES ('HD01', 'MT10', 1);
INSERT INTO CH1.CTHD VALUES ('HD02', 'MT01', 1);
INSERT INTO CH1.CTHD VALUES ('HD02', 'MT02', 1);
INSERT INTO CH1.CTHD VALUES ('HD02', 'MT03', 1);
INSERT INTO CH1.CTHD VALUES ('HD02', 'MT04', 1);
INSERT INTO CH1.CTHD VALUES ('HD02', 'MT05', 1);
INSERT INTO CH1.CTHD VALUES ('HD03', 'MT09', 1);
INSERT INTO CH1.CTHD VALUES ('HD04', 'MT09', 1);
INSERT INTO CH1.CTHD VALUES ('HD05', 'MT09', 1);
INSERT INTO CH1.CTHD VALUES ('HD06', 'MT04', 1);
INSERT INTO CH1.CTHD VALUES ('HD07', 'MT06', 1);
INSERT INTO CH1.CTHD VALUES ('HD08', 'MT09', 1);
INSERT INTO CH1.CTHD VALUES ('HD09', 'MT06', 1);
INSERT INTO CH1.CTHD VALUES ('HD10', 'MT09', 1);

-- Query 1
SELECT MT1.MAMT, TENMT, MAUSAC, DUNGLUONG, NGAYNHAPKHO 
FROM CH1.MAYTINH MT1 JOIN CH1.KHOHANG_QLKHO QL1 ON MT1.MAMT=QL1.MAMT
WHERE THUONGHIEU = 'Dell';

-- Query 2
SELECT DISTINCT(HD1.MAKH) FROM CH1.HOADON HD1
WHERE HD1.MAKH NOT IN (SELECT HD2.MAKH FROM
CH2.HOADON@giamdoc1_dblink HD2)
ORDER BY HD1.MAKH;

-- Query 3
SELECT MAKH
FROM CH1.HOADON HD
WHERE NOT EXISTS (SELECT * FROM CH1.MAYTINH MT
WHERE THUONGHIEU = 'Dell' AND NOT EXISTS (SELECT * FROM CH1.CTHD CT
WHERE CT.MAHD = HD.MAHD AND CT.MAMT = MT.MAMT));

-- Query 4
SELECT MT1.MAMT, TENMT
FROM CH1.MAYTINH MT1 JOIN CH1.KHOHANG_NVBH NVBH1
ON MT1.MAMT = NVBH1.MAMT WHERE TINHTRANG ='Con hang' 
INTERSECT
SELECT MT2.MAMT, MT2.TENMT
FROM CH2.MAYTINH@giamdoc1_dblink MT2 JOIN CH2.KHOHANG_NVBH@giamdoc1_dblink NVBH2 ON MT2.MAMT = NVBH2.MAMT
WHERE TINHTRANG ='Con hang';

--CH2
--Query 5
SELECT MANV, TENNV FROM CH1.NHANVIEN@ch2dblink WHERE LUONG >= 7000000
UNION
SELECT MANV, TENNV FROM CH2.NHANVIEN
WHERE LUONG >=7000000;

-- Query 6
SELECT *
FROM (SELECT CT1.MAMT, TENMT, MAUSAC, MACH, SUM(SOLUONG) FROM CH1.MAYTINH@ch2dblink MT1, CH1.HOADON@ch2dblink HD1, CH1.CTHD@ch2dblink CT1 WHERE MT1.MAMT=CT1.MAMT AND CT1.MAHD=HD1.MAHD AND To_char(NGAYHD,'MM')='10'
GROUP BY CT1.MAMT, TENMT, MAUSAC, MACH
ORDER BY SUM(SOLUONG) DESC)
WHERE ROWNUM <=3
UNION SELECT *
FROM (SELECT CT2.MAMT, TENMT, MAUSAC, MACH, SUM(SOLUONG)
FROM CH2.MAYTINH MT2, CH2.HOADON HD2, CH2.CTHD CT2
WHERE MT2.MAMT=CT2.MAMT AND CT2.MAHD=HD2.MAHD AND To_char(NGAYHD,'MM')='10'
GROUP BY CT2.MAMT, TENMT, MAUSAC, MACH ORDER BY SUM(SOLUONG) DESC)
WHERE ROWNUM <=3;

-- Query 7
SELECT HD1.MACH, SUM(THANHTIEN) DOANH_THU
FROM CH1.HOADON@ch2dblink HD1
WHERE To_char(NGAYHD,'MM')='10' GROUP BY HD1.MACH
UNION
SELECT HD2.MACH, SUM(THANHTIEN) DOANH_THU
FROM CH2.HOADON HD2
WHERE To_char(NGAYHD,'MM')='10' GROUP BY HD2.MACH;

--Query 8
SELECT MAMT, TENMT FROM CH1.MAYTINH@ch2dblink
WHERE MAMT NOT IN (SELECT MAMT FROM CH1.CTHD@ch2dblink)
INTERSECT
SELECT MAMT, TENMT FROM CH2. MAYTINH
WHERE MAMT NOT IN (SELECT MAMT FROM CH2.CTHD);

-- Query 9
SELECT A.MAMT, TENMT, COUNT(MACH)
FROM ( SELECT MACH, MT2.MAMT, TENMT
FROM CH2.MAYTINH MT2, CH2.KHOHANG_NVBH NVBH2
WHERE MT2.MAMT = NVBH2.MAMT
AND TINHTRANG ='Con hang' AND GIATIEN < 20000000
UNION
SELECT MACH, MT1.MAMT, TENMT
FROM CH1.MAYTINH@ch2dblink MT1, CH1.KHOHANG_NVBH@ch2dblink NVBH1
WHERE MT1.MAMT = NVBH1.MAMT
AND TINHTRANG ='Con hang' AND GIATIEN < 20000000) A
GROUP BY A.MAMT, TENMT;

--Query 10
SELECT CT.MAMT, TENMT, SUM(SOLUONG) FROM CH2.MAYTINH MT, CH2.CTHD CT WHERE CT.MAMT = MT.MAMT
GROUP BY CT.MAMT, TENMT
HAVING SUM(SOLUONG) >= ALL
(SELECT SUM(SOLUONG) FROM CH2.CTHD GROUP BY MAMT);


-- T?o Function
-- T�nh t?ng ti?n trong m?t h�a ??n c? th?
    CREATE OR REPLACE FUNCTION TinhTongTien(v_MaHD varchar2)
    RETURN NUMBER
    AS
    V_TONGTIEN NUMBER; 
    BEGIN
    SELECT SUM(CT.SOLUONG * MT.GIATIEN)	INTO V_TONGTIEN
    FROM CH1.CTHD CT JOIN CH1.MAYTINH MT ON CT.MAMT = MT.MAMT
    WHERE MAHD = v_MaHD ;
    RETURN V_TONGTIEN;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
    END;
-- Th?c thi
    DECLARE
    V_MAHD VARCHAR2(10) := 'HD01' ; 
    V_TONGTIEN NUMBER ;
    BEGIN
    V_TONGTIEN :=TinhTongTien(V_MAHD); 
    DBMS_OUTPUT.PUT_LINE('TONG TIEN = ' || V_TONGTIEN );
    END;
set serveroutput on;
-- T?o Procedure
    CREATE OR REPLACE PROCEDURE PROC_FINDCOLOR(v_Color varchar2)
    AS BEGIN
    FOR item IN
    (SELECT MT1.MAMT, MT1.TENMT, MT1.GIATIEN, NVBH1.TINHTRANG,NVBH1.MACH
    FROM CH1.MAYTINH MT1	JOIN CH1.KHOHANG_NVBH NVBH1
    ON MT1.MAMT = NVBH1.MAMT
    WHERE MAUSAC = v_color
    UNION
    SELECT MT2.MAMT, MT2.TENMT, MT2.GIATIEN, NVBH2.TINHTRANG, NVBH2.MACH
    FROM CH2.MAYTINH @giamdoc1_dblink MT2
    JOIN CH2.KHOHANG_NVBH@ giamdoc1_dblink NVBH2	ON MT2.MAMT = NVBH2.MAMT
    WHERE MAUSAC = v_color)
    LOOP
    DBMS_OUTPUT.PUT_LINE('MAMT = ' || item.MAMT 
    || ', Ten MT = ' ||item.TENMT 
    ||',Gia Tien ='||item.GiaTien 
    ||',Tinh Trang ='||item.TinhTrang
    ||',Cua Hang ='||item.MACH);
    END LOOP;
    END;

-- Th?c thi
    DECLARE
    V_Color varchar2(10) := 'Black' ;
    BEGIN
    PROC_FINDCOLOR(V_Color);
    END;
-- t?o trigger
    CREATE OR REPLACE TRIGGER Insert_Update_KhoHang
    AFTER INSERT OR UPDATE OF SOLUONG
    ON KHOHANG_QLKHO
    FOR EACH ROW BEGIN
    CASE
    WHEN UPDATING ('SoLuong') THEN
    IF(:NEW.SoLuong>0) THEN
    UPDATE KHOHANG_NVBH SET TinhTrang = 'Con hang'
    WHERE MaCH = :NEW.MaCH AND MaMT=:NEW.MaMT;
    ELSIF (:NEW.SoLuong<=0) THEN
    UPDATE KHOHANG_NVBH SET TinhTrang = 'Het hang'
    WHERE MaCH = :NEW.MaCH AND MaMT=:NEW.MaMT;
    END IF;
    WHEN INSERTING THEN
    IF(:NEW.SoLuong>0) THEN
    INSERT INTO KHOHANG_NVBH VALUES (:NEW.MaCH, :NEW.MaMT,'Con hang');
    ELSIF (:NEW.SoLuong<=0) THEN
    INSERT INTO KHOHANG_NVBH VALUES(:NEW.MaCH, :NEW.MaMT,'Het hang');
    END IF;
    END CASE;
    END;
    
-- Th?c thi
update KHOHANG_QLKHO set SOLUONG = 100 WHERE MAMT = 'MT05';


commit;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM CH1.MAYTINH WHERE MAMT='MT20';
UPDATE CH1.MAYTINH@CH2DBLINK SET GIATIEN = 30000000 WHERE MAMT =   'MT20';


COMMIT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
UPDATE CH1.MAYTINH SET GIATIEN = 30000000 WHERE MAMT =   'MT20';

COMMIT;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM CH1.KHACHHANG;

COMMIT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
SELECT * FROM CH1.KHACHHANG;
commit;


COMMIT;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM CH1.NHANVIEN WHERE MaNv='NV01';
Update CH1.NhanVien set luong = 10000000 where MaNV = 'NV01';
commit;


COMMIT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
Update CH1.NhanVien set luong = 10000000 where MaNV = 'NV01';
commit;



-- Ph?n 4 t?i ?u h�a c�u truy v?n
-- C�u truy v?n ??n gi?n
select distinct MT.MAMT, MT.TENMT, KQL.SOLUONG, KQL.NGAYNHAPKHO
from CH1.CUAHANG CHA, CH1.KHOHANG_QLKHO KQL, CH1.MAYTINH MT, CH1.KHOHANG_NVBH KNV
WHERE CHA.MACH = KQL.MACH AND KQL.MAMT = MT.MAMT AND MT.MAMT = KNV.MAMT AND MT.GIATIEN > 3000000 AND KNV.TINHTRANG = 'Het hang';

-- Explain query
EXPLAIN PLAN FOR SELECT /*+ GATHER_PLAN_STATISTICS */ distinct MT.MAMT, MT.TENMT, KQL.SOLUONG, KQL.NGAYNHAPKHO
from CH1.CUAHANG CHA, CH1.KHOHANG_QLKHO KQL, CH1.MAYTINH MT, CH1.KHOHANG_NVBH KNV
WHERE CHA.MACH = KQL.MACH AND KQL.MAMT = MT.MAMT AND MT.MAMT = KNV.MAMT AND MT.GIATIEN > 3000000 AND KNV.TINHTRANG = 'Het hang';
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());


-- Explain c�u truy v?n ?� t?i ?u h�a trong m�i tr??ng t?p trung
EXPLAIN PLAN FOR SELECT /*+ GATHER_PLAN_STATISTICS */subtree_left_1.SOLUONG, subtree_left_1.NGAYNHAPKHO, MT.TENMT
FROM (SELECT SOLUONG, NGAYNHAPKHO, MAMT
	FROM (SELECT MACH, SOLUONG, NGAYNHAPKHO, MAMT FROM KHOHANG_QLKHO) KQL
	INNER JOIN (SELECT MACH
			FROM CUAHANG) CH
			ON KQL.MACH = CH.MACH ) subtree_left_1
INNER JOIN (SELECT MAMT, TENMT
		FROM MAYTINH
		WHERE GIATIEN > 3000000) MT
		ON subtree_left_1.MAMT = MT.MAMT
INNER JOIN (SELECT MAMT
		FROM KHOHANG_NVBH
		WHERE TINHTRANG = 'Het hang') KNV
		ON subtree_left_1.MAMT = KNV.MAMT;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

-- Explain c�u truy v?n ?� t?i ?u h�a trong m�i tr??ng ph�n t�n
EXPLAIN PLAN FOR SELECT /*+ GATHER_PLAN_STATISTICS */A.SOLUONG, A.NGAYNHAPKHO, C.TENMT
FROM (SELECT SOLUONG, NGAYNHAPKHO, MAMT, MACH
	FROM CH1.KHOHANG_QLKHO
	UNION
	SELECT SOLUONG, NGAYNHAPKHO, MAMT, MACH
	FROM CH2.KHOHANG_QLKHO@giamdoc1_dblink) A
INNER JOIN (SELECT MAMT, MACH
		FROM CH1.KHOHANG_NVBH KNV
		WHERE TINHTRANG = 'Het hang'
		UNION
		SELECT MAMT, MACH
		FROM CH2.KHOHANG_NVBH@giamdoc1_dblink
		WHERE TINHTRANG = 'Het hang') B
		ON A.MAMT = B.MAMT AND A.MACH = B.MACH
INNER JOIN (SELECT MAMT, TENMT
		FROM CH1.MAYTINH
		WHERE GIATIEN > 3000000) C
		ON B.MAMT = C.MAMT;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());